services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-logs:/usr/share/elasticsearch/logs

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  cerebro:
    image: lmenezes/cerebro:0.9.4
    container_name: cerebro
    depends_on:
      - elasticsearch
    environment:
      - SECRET_KEY=thisIsASuperSecretKeyForLocal
    ports:
      - "9000:9000"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.2
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/config:/usr/share/logstash/config  
      - ./logstash/data:/usr/share/logstash/data  
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m  
    ports:
      - "5044:5044"  
      - "9600:9600"  

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.2
    container_name: filebeat
    user: root
    volumes:
      - ./logstash/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - es-logs:/usr/share/elasticsearch/logs:ro
    networks:
      - default
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200 
    
volumes:
  es-logs:

