services: 
  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    container_name: etl
    volumes:
      - ./data:/data
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=db
      - DB_USER=root
      - DB_PASSWORD=root

  app_flask:
    image: app_flask
    container_name: app_flask
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=db
      - DB_USER=root
      - DB_PASSWORD=root
  
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d/

volumes:
  data:

